In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [46]:
my_list = [1,2,3,4,5,6]

my_list_1 = [[1,2],[3,4],[5,6]]
 

### Numpy Array Creation

In [47]:
array = np.array(my_list, dtype = int)
print(array)
print("\n")
array_1 = np.array(my_list_1, dtype = int)
print(array_1)

[1 2 3 4 5 6]


[[1 2]
 [3 4]
 [5 6]]


In [48]:
print(f"type:{type(array)}")
print(f"len: {len(array)}")
print(f"dimensions: {array.ndim}")
print(f"shape: {array.shape}")
print("\n")
print(f"type:{type(array_1)}")
print(f"len: {len(array_1)}")
print(f"dimensions: {array_1.ndim}")
print(f"shape: {array_1.shape}")

type:<class 'numpy.ndarray'>
len: 6
dimensions: 1
shape: (6,)


type:<class 'numpy.ndarray'>
len: 3
dimensions: 2
shape: (3, 2)


In [50]:
print(array.size) # gives number of elemets in ndarray
print(array_1.size)

6
6


In [52]:
print(array.itemsize) # gives memory size of one element (only) in ndarray in bytes
print(array_1.itemsize)

4
4


In [9]:
array.size * array.itemsize # gives total memory of the array in bytes

24

In [10]:
array.nbytes # gives total memory of the array in bytes

24

# 
Reshaping Numpy Array using..... array_name.reshape(rows,columns)

returns a reshaped array, but does not modify the original array


In [11]:
array2 = array.reshape(3,2)
print(array2)
print(f"shape: {array2.shape}")
print(array)
print(f"original array shape: {array.shape}")

[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)
[1 2 3 4 5 6]
original array shape: (6,)


If anyone (either row or column) is given as -1, then that dimension is calculated automatically...
however the othe dimension needs to be specified

In [12]:
print(array.reshape(3,-1))
print("\n")
print(array.reshape(-1,3))

[[1 2]
 [3 4]
 [5 6]]


[[1 2 3]
 [4 5 6]]


# 
Initializing numpy arrays from nested lists ... all lists must be nested in a single list as numpy arrays requires a singlr list

In [53]:
my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [3,4,5,6,7]

In [54]:
mul_arr = np.array([my_list2, my_list3, my_list4])
print(mul_arr) 
print(f"shape: {mul_arr.shape}")

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
shape: (3, 5)


In [59]:
mul_arr.reshape(-1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [62]:
print(mul_arr)
print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
(3, 5)


### Numpy attributes

In [16]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


# 
The below method of reshaping modifies the original array to the shape

In [17]:
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# 
creating numpy array from range

In [63]:
b = np.arange(24)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [67]:
b.shape = (6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


### Numpy Arithmetic operations... Note, these cannot be performed on normal lists

In [20]:
x = np.array([[1,2],[3,4]], dtype= float)
y = np.array([[5,6],[7,8]], dtype= float)
z = np.array([[2,2],[3,3]], dtype= float)

print(x)
print(y)
print(z)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[2. 2.]
 [3. 3.]]


#### numpy.add()  /  numpy.subtract() - performs elementwise addition / subtraction between 2 arrays
Syntax: numpy.add(arr_1,arr_2)... two arrays only

In [21]:
print(x+y)
print(x-y)
print("\n")
print(np.add(x,y))
print("\n")
print(np.subtract(x,y))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]


[[ 6.  8.]
 [10. 12.]]


[[-4. -4.]
 [-4. -4.]]


#### numpy.multiply() / numpy.divide()- performs elementwise multiplication / Division between 2 arrays
Syntax numpy.multiply(arr_1,arr_2)... two arrays only

In [22]:
print(x*y)
print(x/y)

print("\n")
print(np.multiply(x,y))
print("\n")
print(np.divide(x,y))

[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[ 5. 12.]
 [21. 32.]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]


In [24]:
print(np.cross(x,y))

[-4. -4.]


In [25]:
np.power(x,y)

array([[1.0000e+00, 6.4000e+01],
       [2.1870e+03, 6.5536e+04]])

In [72]:
x = np.array([[-1,2],[3,4]], dtype= float)
y = np.array([[5,6],[7,-8]], dtype= float)
z = np.array([[2,2],[3,3]], dtype= float)

print(x)
print(y)
print(z)

[[-1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7. -8.]]
[[2. 2.]
 [3. 3.]]


In [73]:
np.floor(x/y)

array([[-1.,  0.],
       [ 0., -1.]])

In [74]:
np.negative(x)

array([[ 1., -2.],
       [-3., -4.]])

In [75]:
np.positive(x)

array([[-1.,  2.],
       [ 3.,  4.]])

In [76]:
np.remainder(x,y)

array([[ 4.,  2.],
       [ 3., -4.]])

In [80]:
np.mod(x,y)

array([[ 4.,  2.],
       [ 3., -4.]])

### numpy.sum(array, axis (optional) = 0(Y axis) or 1(X axis)) -
returns a sum of all array elements os sum of all array elements over a given axis

In [31]:
print(np.sum(x))
print(np.sum(x, axis = 0)) # sum of each column
print(np.sum(x, axis = 1)) # sum of each row

10.0
[4. 6.]
[3. 7.]


In [32]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [33]:
print(np.median(x))
print(np.median(x, axis=0))
print(np.median(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [34]:
help(nbytes)


NameError: name 'nbytes' is not defined

In [83]:
sample_str = "Sundar"
print(sample_str)
sample_str.replace("a","e")
print(sample_str)
sample_str =  sample_str.replace("a","e")
print(sample_str)

Sundar
Sundar
Sunder


In [86]:
print(5//-2)

-3


In [96]:
abc = {5,6,1,1,"as"}
efg = [7,8,9]
xyz = {99,55,87,"asdfg"}

abc.update(xyz)
print(abc)

{1, 99, 5, 6, 55, 'as', 87, 'asdfg'}


In [2]:
 ls = [1, 2, 3, 3, 2, 3, 1, 4, 5, 6, 5, 6, 3, 2, 1, 1, 1, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 10, 10, 1, 2, 3, 9, 10]

In [3]:
s = set(ls)
print(s)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [173]:
x = "Welcome to the Python course!"
y = "Python programming is used in the course!"

x_ls = x.split(" ")
y_ls = y.split(" ")

red = [x1 for x1 in x_ls for y1 in y_ls if x1==y1]
print(red)

['the', 'Python', 'course!']


In [4]:
tup = 'sam',4,5

In [5]:
print(type(tup))

<class 'tuple'>


In [27]:
lst = [1,2,3,4,5]

In [29]:
lst.append(ls)
print(lst)

[1, 2, 3, 4, 5, 1, 2, 3, 3, 2, 3, 1, 4, 5, 6, 5, 6, 3, 2, 1, 1, 1, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9, 10, 10, 1, 2, 3, 9, 10]


In [88]:
final  = ""
x = "Mathematics is essential in many fields"

x_upd = x.split(" ")
print(x_upd)
x_upd = [elem[::-1] for elem in x_upd]
print(x_upd)

for elem in x_upd:
    final+=elem + " "
    
print(final)

['Mathematics', 'is', 'essential', 'in', 'many', 'fields']
['scitamehtaM', 'si', 'laitnesse', 'ni', 'ynam', 'sdleif']
scitamehtaM si laitnesse ni ynam sdleif 


In [81]:
s = "Lists are mutable sequences, typically used to store collections of homogeneous items."
x = list(s.lower())
print({char:x.count(char) for char in x if char.isalpha()})

{'l': 6, 'i': 4, 's': 9, 't': 7, 'a': 3, 'r': 2, 'e': 11, 'm': 3, 'u': 4, 'b': 1, 'q': 1, 'n': 3, 'c': 4, 'y': 2, 'p': 1, 'd': 1, 'o': 8, 'f': 1, 'h': 1, 'g': 1}
